In [2]:
import pandas as pd
import numpy as np

In [6]:
ICD_9_hip_fracture_codes = ['73315','73314','73381','73382','73396','8081','820','82001','82002','82003','82009','82010','82011','82012','82013','82019','82020','82021','82022','82030','82031','82032','8208','8209']
ICD_10_hip_fracture_codes = ['M80051G','M80051A','M80051K','M80051P','M80052A','M80052G','M80052K','M80052P','M80059A','M80059G','M80059K','M80059P','M80851A','M80851G','M80851K','M80851P','M80852A','M80852G','M80852K','M80852P','M80859A','M80859G','M80859K','M80859P','M84351A','M84351K','M84351P','M84352A','M84352K','M84352P','M84353A','M84353K','M84353P','M84359A','M84359K','M84359P','M84451A','M84451K','M84451P','M84452A','M84452K','M84452P','M84453A','M84453K','M84453P','M84459A','M84459K','M84459P','M84551A','M84551K','M84551P','M84552A','M84552K','M84552P','M84553A','M84553K','M84553P','M84559A','M84559K','M84559P','M84651A','M84651K','M84651P','M84652A','M84652K','M84652P','M84653A','M84653K','M84653P','M84659A','M84659K','M84659P','M84750A','M84750G','M84750K','M84750P','M84751A','M84751G','M84751K','M84751P','M84752A','M84752G','M84752K','M84752P','M84753A','M84753G','M84753K','M84753P','M84754A','M84754G','M84754K','M84754P','M84755A','M84755G','M84755K','M84755P','M84756A','M84756G','M84756K','M84756P','M84757A','M84757G','M84757K','M84757P','M84758A','M84758G','M84758K','M84758P','M84759A','M84759G','M84759K','M84759P','S32401A','S32401B','S32401G','S32401K','S32402A','S32402B','S32402G','S32402K','S32409A','S32409B','S32409G','S32409K','S32411A','S32411B','S32411G','S32411K','S32412A','S32412B','S32412G','S32412K','S32413A','S32413B','S32413G','S32413K','S32414A','S32414B','S32414G','S32414K','S32415A','S32415B','S32415G','S32415K','S32416A','S32416B','S32416G','S32416K','S32421A','S32421B','S32421G','S32421K','S32422A','S32422B','S32422G','S32422K','S32423A','S32423B','S32423G','S32423K','S32424A','S32424B','S32424G','S32424K','S32425A','S32425B','S32425G','S32425K','S32426A','S32426B','S32426G','S32426K','S32431A','S32431B','S32431G','S32431K','S32432A','S32432B','S32432G','S32432K','S32433A','S32433B','S32433G','S32433K','S32434A','S32434B','S32434G','S32434K','S32435A','S32435B','S32435G','S32435K','S32436A','S32436B','S32436G','S32436K','S32441A','S32441B','S32441G','S32441K','S32442A','S32442B','S32442G','S32442K','S32443A','S32443B','S32443G','S32443K','S32444A','S32444B','S32444G','S32444K','S32445A','S32445B','S32445G','S32445K','S32446A','S32446B','S32446G','S32446K','S32451A','S32451B','S32451G','S32451K','S32452A','S32452B','S32452G','S32452K','S32453A','S32453B','S32453G','S32453K','S32454A','S32454B','S32454G','S32454K','S32455A','S32455B','S32455G','S32455K','S32456A','S32456B','S32456G','S32456K','S32461A','S32461B','S32461G','S32461K','S32462A','S32462B','S32462G','S32462K','S32463A','S32463B','S32463G','S32463K','S32464A','S32464B','S32464G','S32464K','S32465A','S32465B','S32465G','S32465K','S32466A','S32466B','S32466G','S32466K','S32471A','S32471B','S32471G','S32471K','S32472A','S32472B','S32472G','S32472K','S32473A','S32473B','S32473G','S32473K','S32474A','S32474B','S32474G','S32474K','S32475A','S32475B','S32475G','S32475K','S32476A','S32476B','S32476G','S32476K','S32481A','S32481B','S32481G','S32481K','S32482A','S32482B','S32482G','S32482K','S32483A','S32483B','S32483G','S32483K','S32484A','S32484B','S32484G','S32484K','S32485A','S32485B','S32485G','S32485K','S32486A','S32486B','S32486G','S32486K','S32491A','S32491B','S32491G','S32491K','S32492A','S32492B','S32492G','S32492K','S32499A','S32499B','S32499G','S32499K','S72001A','S72001B','S72001C','S72001G','S72001H','S72001J','S72001K','S72001M','S72001N','S72001P','S72001Q','S72001R','S72002A','S72002B','S72002C','S72002G','S72002H','S72002J','S72002K','S72002M','S72002N','S72002P','S72002Q','S72002R','S72009A','S72009B','S72009C','S72009G','S72009H','S72009J','S72009K','S72009M','S72009N','S72009P','S72009Q','S72009R','S72011A','S72011B','S72011C','S72011G','S72011H','S72011J','S72011K','S72011M','S72011N','S72011P','S72011Q','S72011R','S72012A','S72012B','S72012C','S72012G','S72012H','S72012J','S72012K','S72012M','S72012N','S72012P','S72012Q','S72012R','S72019A','S72019B','S72019C','S72019G','S72019H','S72019J','S72019K','S72019M','S72019N','S72019P','S72019Q','S72019R','S72021A','S72021B','S72021C','S72021G','S72021H','S72021J','S72021K','S72021M','S72021N','S72021P','S72021Q','S72021R','S72022A','S72022B','S72022C','S72022G','S72022H','S72022J','S72022K','S72022M','S72022N','S72022P','S72022Q','S72022R','S72023A','S72023B','S72023C','S72023G','S72023H','S72023J','S72023K','S72023M','S72023N','S72023P','S72023Q','S72023R','S72024A','S72024B','S72024C','S72024G','S72024H','S72024J','S72024K','S72024M','S72024N','S72024P','S72024Q','S72024R','S72025A','S72025B','S72025C','S72025G','S72025H','S72025J','S72025K','S72025M','S72025N','S72025P','S72025Q','S72025R','S72026A','S72026B','S72026C','S72026G','S72026H','S72026J','S72026K','S72026M','S72026N','S72026P','S72026Q','S72026R','S72031A','S72031B','S72031C','S72031G','S72031H','S72031J','S72031K','S72031M','S72031N','S72031P','S72031Q','S72031R','S72032A','S72032B','S72032C','S72032G','S72032H','S72032J','S72032K','S72032M','S72032N','S72032P','S72032Q','S72032R','S72033A','S72033B','S72033C','S72033G','S72033H','S72033J','S72033K','S72033M','S72033N','S72033P','S72033Q','S72033R','S72034A','S72034B','S72034C','S72034G','S72034H','S72034J','S72034K','S72034M','S72034N','S72034P','S72034Q','S72034R','S72035A','S72035B','S72035C','S72035G','S72035H','S72035J','S72035K','S72035M','S72035N','S72035P','S72035Q','S72035R','S72036A','S72036B','S72036C','S72036G','S72036H','S72036J','S72036K','S72036M','S72036N','S72036P','S72036Q','S72036R','S72041A','S72041B','S72041C','S72041G','S72041H','S72041J','S72041K','S72041M','S72041N','S72041P','S72041Q','S72041R','S72042A','S72042B','S72042C','S72042G','S72042H','S72042J','S72042K','S72042M','S72042N','S72042P','S72042Q','S72042R','S72043A','S72043B','S72043C','S72043G','S72043H','S72043J','S72043K','S72043M','S72043N','S72043P','S72043Q','S72043R','S72044A','S72044B','S72044C','S72044G','S72044H','S72044J','S72044K','S72044M','S72044N','S72044P','S72044Q','S72044R','S72045A','S72045B','S72045C','S72045G','S72045H','S72045J','S72045K','S72045M','S72045N','S72045P','S72045Q','S72045R','S72046A','S72046B','S72046C','S72046G','S72046H','S72046J','S72046K','S72046M','S72046N','S72046P','S72046Q','S72046R','S72051A','S72051B','S72051C','S72051G','S72051H','S72051J','S72051K','S72051M','S72051N','S72051P','S72051Q','S72051R','S72052A','S72052B','S72052C','S72052G','S72052H','S72052J','S72052K','S72052M','S72052N','S72052P','S72052Q','S72052R','S72059A','S72059B','S72059C','S72059G','S72059H','S72059J','S72059K','S72059M','S72059N','S72059P','S72059Q','S72059R','S72061A','S72061B','S72061C','S72061G','S72061H','S72061J','S72061K','S72061M','S72061N','S72061P','S72061Q','S72061R','S72062A','S72062B','S72062C','S72062G','S72062H','S72062J','S72062K','S72062M','S72062N','S72062P','S72062Q','S72062R','S72063A','S72063B','S72063C','S72063G','S72063H','S72063J','S72063K','S72063M','S72063N','S72063P','S72063Q','S72063R','S72064A','S72064B','S72064C','S72064G','S72064H','S72064J','S72064K','S72064M','S72064N','S72064P','S72064Q','S72064R','S72065A','S72065B','S72065C','S72065G','S72065H','S72065J','S72065K','S72065M','S72065N','S72065P','S72065Q','S72065R','S72066A','S72066B','S72066C','S72066G','S72066H','S72066J','S72066K','S72066M','S72066N','S72066P','S72066Q','S72066R','S72091A','S72091B','S72091C','S72091G','S72091H','S72091J','S72091K','S72091M','S72091N','S72091P','S72091Q','S72091R','S72092A','S72092B','S72092C','S72092G','S72092H','S72092J','S72092K','S72092M','S72092N','S72092P','S72092Q','S72092R','S72099A','S72099B','S72099C','S72099G','S72099H','S72099J','S72099K','S72099M','S72099N','S72099P','S72099Q','S72099R','S72101A','S72101B','S72101C','S72101G','S72101H','S72101J','S72101K','S72101M','S72101N','S72101P','S72101Q','S72101R','S72102A','S72102B','S72102C','S72102G','S72102H','S72102J','S72102K','S72102M','S72102N','S72102P','S72102Q','S72102R','S72109A','S72109B','S72109C','S72109G','S72109H','S72109J','S72109K','S72109M','S72109N','S72109P','S72109Q','S72109R','S72111A','S72111B','S72111C','S72111G','S72111H','S72111J','S72111K','S72111M','S72111N','S72111P','S72111Q','S72111R','S72112A','S72112B','S72112C','S72112G','S72112H','S72112J','S72112K','S72112M','S72112N','S72112P','S72112Q','S72112R','S72113A','S72113B','S72113C','S72113G','S72113H','S72113J','S72113K','S72113M','S72113N','S72113P','S72113Q','S72113R','S72114A','S72114B','S72114C','S72114G','S72114H','S72114J','S72114K','S72114M','S72114N','S72114P','S72114Q','S72114R','S72115A','S72115B','S72115C','S72115G','S72115H','S72115J','S72115K','S72115M','S72115N','S72115P','S72115Q','S72115R','S72116A','S72116B','S72116C','S72116G','S72116H','S72116J','S72116K','S72116M','S72116N','S72116P','S72116Q','S72116R','S72121A','S72121B','S72121C','S72121G','S72121H','S72121J','S72121K','S72121M','S72121N','S72121P','S72121Q','S72121R','S72122A','S72122B','S72122C','S72122G','S72122H','S72122J','S72122K','S72122M','S72122N','S72122P','S72122Q','S72122R','S72123A','S72123B','S72123C','S72123G','S72123H','S72123J','S72123K','S72123M','S72123N','S72123P','S72123Q','S72123R','S72124A','S72124B','S72124C','S72124G','S72124H','S72124J','S72124K','S72124M','S72124N','S72124P','S72124Q','S72124R','S72125A','S72125B','S72125C','S72125G','S72125H','S72125J','S72125K','S72125M','S72125N','S72125P','S72125Q','S72125R','S72126A','S72126B','S72126C','S72126G','S72126H','S72126J','S72126K','S72126M','S72126N','S72126P','S72126Q','S72126R','S72131A','S72131B','S72131C','S72131G','S72131H','S72131J','S72131K','S72131M','S72131N','S72131P','S72131Q','S72131R','S72132A','S72132B','S72132C','S72132G','S72132H','S72132J','S72132K','S72132M','S72132N','S72132P','S72132Q','S72132R','S72133A','S72133B','S72133C','S72133G','S72133H','S72133J','S72133K','S72133M','S72133N','S72133P','S72133Q','S72133R','S72134A','S72134B','S72134C','S72134G','S72134H','S72134J','S72134K','S72134M','S72134N','S72134P','S72134Q','S72134R','S72135A','S72135B','S72135C','S72135G','S72135H','S72135J','S72135K','S72135M','S72135N','S72135P','S72135Q','S72135R','S72136A','S72136B','S72136C','S72136G','S72136H','S72136J','S72136K','S72136M','S72136N','S72136P','S72136Q','S72136R','S72141A','S72141B','S72141C','S72141G','S72141H','S72141J','S72141K','S72141M','S72141N','S72141P','S72141Q','S72141R','S72142A','S72142B','S72142C','S72142G','S72142H','S72142J','S72142K','S72142M','S72142N','S72142P','S72142Q','S72142R','S72143A','S72143B','S72143C','S72143G','S72143H','S72143J','S72143K','S72143M','S72143N','S72143P','S72143Q','S72143R','S72144A','S72144B','S72144C','S72144G','S72144H','S72144J','S72144K','S72144M','S72144N','S72144P','S72144Q','S72144R','S72145A','S72145B','S72145C','S72145G','S72145H','S72145J','S72145K','S72145M','S72145N','S72145P','S72145Q','S72145R','S72146A','S72146B','S72146C','S72146G','S72146H','S72146J','S72146K','S72146M','S72146N','S72146P','S72146Q','S72146R','S7221XA','S7221XB','S7221XC','S7221XG','S7221XH','S7221XJ','S7221XK','S7221XM','S7221XN','S7221XP','S7221XQ','S7221XR','S7222XA','S7222XB','S7222XC','S7222XG','S7222XH','S7222XJ','S7222XK','S7222XM','S7222XN','S7222XP','S7222XQ','S7222XR','S7223XA','S7223XB','S7223XC','S7223XG','S7223XH','S7223XJ','S7223XK','S7223XM','S7223XN','S7223XP','S7223XQ','S7223XR','S7224XA','S7224XB','S7224XC','S7224XG','S7224XH','S7224XJ','S7224XK','S7224XM','S7224XN','S7224XP','S7224XQ','S7224XR','S7225XA','S7225XB','S7225XC','S7225XG','S7225XH','S7225XJ','S7225XK','S7225XM','S7225XN','S7225XP','S7225XQ','S7225XR','S7226XA','S7226XB','S7226XC','S7226XG','S7226XH','S7226XJ','S7226XK','S7226XM','S7226XN','S7226XP','S7226XQ','S7226XR','S79001A','S79001G','S79001K','S79001P','S79002A','S79002G','S79002K','S79002P','S79009A','S79009G','S79009K','S79009P','S79011A','S79011G','S79011K','S79011P','S79012A','S79012G','S79012K','S79012P','S79019A','S79019G','S79019K','S79019P','S79091A','S79091G','S79091K','S79091P','S79092A','S79092G','S79092K','S79092P','S79099A','S79099G','S79099K','S79099P']
all_hip_fracture_codes = ICD_9_hip_fracture_codes + ICD_10_hip_fracture_codes
hip_fracture_codes_df = pd.DataFrame(all_hip_fracture_codes)
# hip_fracture_codes_df.to_csv('hip_fracture_ICD_diagnosis_codes.csv')
# test = pd.read_csv('hip_fracture_codes_csv')
# test

In [7]:
# loading diagnoses
diagnoses_icd = pd.read_csv('/Volumes/GMA Personal/mimic-iv-1.0/hosp/diagnoses_icd.csv')

# filtering diagnoses csv
filtered_diagnoses = diagnoses_icd[diagnoses_icd['icd_code'].isin(all_hip_fracture_codes)]
filtered_diagnoses
HF_unique_subject_IDs = filtered_diagnoses['subject_id'].unique()
HF_unique_subject_IDs_series = pd.Series(HF_unique_subject_IDs)
#print(type(HF_unique_subject_IDs))
#print(len(filtered_diagnoses))

# summarizing by count of unique subject IDs
summary_diagnoses = filtered_diagnoses.groupby('subject_id').count()
summary_diagnoses = summary_diagnoses.sort_values(by='icd_version',ascending=False)
# summary_diagnoses

# to do: look into the number of unique patients in this entire database. 3700 may be too small of a universe
#filtered_diagnoses.to_csv()

In [21]:
# loading admissions
admissions = pd.read_csv('/Volumes/GMA Personal/mimic-iv-1.0/core/admissions.csv')

# filtering admissions
filtered_admissions = admissions[admissions['subject_id'].isin(HF_unique_subject_IDs)]

# summarizing by count of unique subject IDs
summary_admissions = filtered_admissions.groupby('subject_id').count()
summary_admissions = summary_admissions.sort_values(by='hadm_id',ascending=False)
# summary_admissions
filtered_admissions.columns

Index(['subject_id', 'hadm_id', 'admittime', 'dischtime', 'deathtime',
       'admission_type', 'admission_location', 'discharge_location',
       'insurance', 'language', 'marital_status', 'ethnicity', 'edregtime',
       'edouttime', 'hospital_expire_flag'],
      dtype='object')

In [19]:
# loading procedures
procedures = pd.read_csv('/Volumes/GMA Personal/mimic-iv-1.0/hosp/procedures_icd.csv')

# filtering procedures
filtered_procedures = procedures[procedures['subject_id'].isin(HF_unique_subject_IDs)]

# summarizing by count of unique subject IDs
summary_procedures = filtered_procedures.groupby('subject_id').count()
summary_procedures = summary_procedures.sort_values(by='hadm_id',ascending=False)
# summary_procedures
filtered_procedures.columns

/Users/gmasrian/opt/anaconda3/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

Index(['subject_id', 'hadm_id', 'seq_num', 'chartdate', 'icd_code',
       'icd_version'],
      dtype='object')

In [22]:
# loading icustays
icustays = pd.read_csv('/Volumes/GMA Personal/mimic-iv-1.0/icu/icustays.csv')

# filtering icustays
filtered_icustays = icustays[icustays['subject_id'].isin(HF_unique_subject_IDs)]

# summarizing by count of unique subject IDs
summary_icustays = filtered_icustays.groupby('subject_id').count()
summary_icustays = summary_icustays.sort_values(by='hadm_id',ascending=False)
# summary_icustays
filtered_icustays.columns

Index(['subject_id', 'hadm_id', 'stay_id', 'first_careunit', 'last_careunit',
       'intime', 'outtime', 'los'],
      dtype='object')

In [28]:
# loading procedureevents - from icu
icu_procedureevents = pd.read_csv('/Volumes/GMA Personal/mimic-iv-1.0/icu/procedureevents.csv')

# filtering procedureevents
filtered_icu_procedureevents = icu_procedureevents[icu_procedureevents['subject_id'].isin(HF_unique_subject_IDs)]

# summarizing by count of unique subject IDs
summary_icu_procedureevents = filtered_icu_procedureevents.groupby('subject_id').count()
summary_icu_procedureevents = summary_icu_procedureevents.sort_values(by='hadm_id',ascending=False)
# summary_procedureevents
filtered_icu_procedureevents

,subject_id,hadm_id,stay_id,starttime,endtime,storetime,itemid,value,valueuom,location,...,patientweight,totalamount,totalamountuom,isopenbag,continueinnextdept,cancelreason,statusdescription,comments_date,originalamount,originalrate
356,15110026,28089871,38700117,2142-03-26 20:00:00,2142-03-27 21:57:00,2142-03-27 22:07:00,224274,1557.0,min,RL Post Forearm,...,85.1,NaN,NaN,1,0,0,FinishedRunning,NaN,1557.0,1
357,15110026,28089871,38700117,2142-03-27 12:12:00,2142-03-28 16:59:00,2142-03-28 16:59:24.21,224264,1727.0,min,NaN,...,85.1,NaN,NaN,1,0,0,FinishedRunning,NaN,1727.0,1
358,15110026,28089871,38700117,2142-03-27 13:15:00,2142-03-28 16:59:00,2142-03-28 16:59:24.21,225441,1664.0,min,NaN,...,85.1,NaN,NaN,1,0,0,FinishedRunning,NaN,1664.0,1
359,15110026,28089871,38700117,2142-03-28 03:53:00,2142-03-28 03:54:00,2142-03-28 03:53:00,225459,1.0,None,NaN,...,85.1,NaN,NaN,0,0,0,FinishedRunning,NaN,1.0,0
447,10546500,20839562,38712665,2169-10-23 00:00:00,2169-10-23 01:10:00,2169-10-23 02:41:00,224276,70.0,min,NaN,...,75.0,NaN,NaN,1,0,0,FinishedRunning,NaN,70.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
730492,17634362,25842862,37309730,2162-06-08 16:16:00,2162-06-08 20:03:00,2162-06-08 20:03:58.983,224274,227.0,min,NaN,...,86.0,NaN,NaN,1,0,0,FinishedRunning,NaN,227.0,1
730519,14032639,26601900,38235319,2137-04-08 17:30:00,2137-04-09 22:22:00,2137-04-09 22:22:41.88,224275,1732.0,min,NaN,...,100.5,NaN,NaN,1,0,0,FinishedRunning,NaN,1732.0,1
730520,14032639,26601900,38235319,2137-04-08 17:30:00,2137-04-09 22:22:00,2137-04-09 22:22:41.88,224275,1732.0,min,NaN,...,100.5,NaN,NaN,1,0,0,FinishedRunning,NaN,1732.0,1
730521,14032639,26601900,38235319,2137-04-08 17:30:00,2137-04-09 22:22:00,2137-04-09 22:22:41.88,224275,1732.0,min,NaN,...,100.5,NaN,NaN,1,0,0,FinishedRunning,NaN,1732.0,1
730522,14032639,26601900,38235319,2137-04-08 17:32:00,2137-04-08 17:33:00,2137-04-08 17:32:00,229579,1.0,None,NaN,...,100.5,NaN,NaN,0,0,0,FinishedRunning,NaN,1.0,0

In [31]:
# loading prescriptions
prescriptions = pd.read_csv('/Volumes/GMA Personal/mimic-iv-1.0/hosp/prescriptions.csv')

# filtering prescriptions
filtered_prescriptions = prescriptions[prescriptions['subject_id'].isin(HF_unique_subject_IDs)]

# summarizing by count of unique subject IDs
summary_prescriptions = filtered_prescriptions.groupby('subject_id').count()
summary_prescriptions = summary_prescriptions.sort_values(by='hadm_id',ascending=False)
# summary_prescriptions

# filtered_prescriptions.columns
# investigate the patients' prescriptions if they're outliers (in terms of #)
outlier_rx = filtered_prescriptions[filtered_prescriptions['subject_id']==13297743]
outlier_rx.to_csv('outlier_rx.csv')
# outlier_rx.to_csv('outlier_rx.csv')

/Users/gmasrian/opt/anaconda3/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [27]:
# loading patients
patients = pd.read_csv('/Volumes/GMA Personal/mimic-iv-1.0/core/patients.csv')

# filtering patients
filtered_patients = patients[patients['subject_id'].isin(HF_unique_subject_IDs)]

# summarizing by count of unique subject IDs
summary_patients = filtered_patients.groupby('subject_id').count()
summary_patients = summary_patients.sort_values(by='gender',ascending=False)
summary_patients

            gender  anchor_age  anchor_year  anchor_year_group  dod
subject_id
10000117         1           1            1                  1    0
16826165         1           1            1                  1    0
16800398         1           1            1                  1    0
16800514         1           1            1                  1    0
16806409         1           1            1                  1    0
...            ...         ...          ...                ...  ...
13390054         1           1            1                  1    0
13390581         1           1            1                  1    0
13391979         1           1            1                  1    0
13396426         1           1            1                  1    0
19998497         1           1            1                  1    0

[3752 rows x 5 columns]

            gender  anchor_age  anchor_year  anchor_year_group  dod
subject_id
10000117         1           1            1                  1    0
16826165         1           1            1                  1    0
16800398         1           1            1                  1    0
16800514         1           1            1                  1    0
16806409         1           1            1                  1    0
...            ...         ...          ...                ...  ...
13390054         1           1            1                  1    0
13390581         1           1            1                  1    0
13391979         1           1            1                  1    0
13396426         1           1            1                  1    0
19998497         1           1            1                  1    0

[3752 rows x 5 columns]

In [15]:
# loading hcpcsevents (hosp)
hcpcs = pd.read_csv('/Volumes/GMA Personal/mimic-iv-1.0/hosp/hcpcsevents.csv')

# filtering hcpcsevents (hosp)
filtered_hcpcs = hcpcs[hcpcs['subject_id'].isin(HF_unique_subject_IDs)]


# summarizing by count of unique subject IDs
summary_hcpcs = filtered_hcpcs.groupby('subject_id').count()
summary_hcpcs = summary_hcpcs.sort_values(by='hadm_id',ascending=False)
summary_hcpcs.head()

,subject_id,hadm_id,chartdate,hcpcs_cd,seq_num,short_description
72088,19143338,21565955,2171-12-01,27244,1,Musculoskeletal system
96486,15452718,28911265,2170-10-07,27244,1,Musculoskeletal system
99527,18453702,22000751,2133-03-22,27130,1,Musculoskeletal system
134809,15701421,22863510,2185-06-06,27238,1,Musculoskeletal system
148968,10002428,28676446,2157-07-16,27235,1,Musculoskeletal system
152934,15336593,22053902,2143-12-05,27236,1,Musculoskeletal system

In [11]:
# loading hcpcsevents (hosp)
hcpcs = pd.read_csv('/Volumes/GMA Personal/mimic-iv-1.0/hosp/hcpcsevents.csv')

# filtering hcpcsevents (hosp)
filtered_hcpcs = hcpcs[hcpcs['subject_id'].isin(HF_unique_subject_IDs)]


# summarizing by count of unique subject IDs
summary_hcpcs = filtered_hcpcs.groupby('subject_id').count()
summary_hcpcs = summary_hcpcs.sort_values(by='hadm_id',ascending=False)
filtered_hcpcs.columns

Index(['subject_id', 'hadm_id', 'chartdate', 'hcpcs_cd', 'seq_num',
       'short_description'],
      dtype='object')

In [20]:
# loading procedures_icd (hosp)
procedures_icd = pd.read_csv('/Volumes/GMA Personal/mimic-iv-1.0/hosp/procedures_icd.csv')

# filtering hcpcsevents (hosp)
filtered_procedures_icd = procedures_icd[procedures_icd['subject_id'].isin(HF_unique_subject_IDs)]


# summarizing by count of unique subject IDs
summary_procedures_icd = procedures_icd.groupby('subject_id').count()
summary_procedures_icd = summary_procedures_icd.sort_values(by='hadm_id',ascending=False)
filtered_procedures_icd.columns

/Users/gmasrian/opt/anaconda3/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

Index(['subject_id', 'hadm_id', 'seq_num', 'chartdate', 'icd_code',
       'icd_version'],
      dtype='object')

In [ ]:
# loading chartevents
chartevents = pd.read_csv('/Volumes/GMA Personal/mimic-iv-1.0/icu/chartevents.csv')
len(chartevents)
# # filtering chartevents
# filtered_chartevents = chartevents[chartevents['subject_id'].isin(HF_unique_subject_IDs)]

# summarizing by count of unique subject IDs
# summary_chartevents = filtered_chartevents.groupby('subject_id').count()
# summary_chartevents = summary_chartevents.sort_values(by='gender',ascending=False)

In [23]:
# trying to filter for ICD Procedure codes in this link:
# https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5649370/#:~:text=The%20final%20specific%20procedural%20codes,%2C%2027240%2C%2027244%2C%2027245.
procedures_icd = pd.read_csv('/Volumes/GMA Personal/mimic-iv-1.0/hosp/procedures_icd.csv')
icd_pcs = ['8151','8152','7855','7905','7915','7925','7935','7965']
procedures_icd = procedures_icd[procedures_icd['icd_code'].isin(icd_pcs)]
icd_procedures_subject_id_ser = procedures_icd.subject_id
# subject_id_additions_ser

# filtering for hcpcs procedures
# using this link as a guide for the codes: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5649370/#:~:text=The%20final%20specific%20procedural%20codes,%2C%2027240%2C%2027244%2C%2027245.
hcpcs_copy = hcpcs
hip_hcpcs_list = ['27125','27130','27230','27232','27235','27236','27246','27248','73530','27238','27240','27244','27245']
hcpcs_hip_table = hcpcs_copy[hcpcs_copy['hcpcs_cd'].isin(hip_hcpcs_list)]
hcpcs_hip_table
subject_ids_from_hcpcs = hcpcs_hip_table.subject_id
# type(subject_ids_from_hcpcs)

# combining the additions
# subject_id_additions = pd.merge(subject_id_additions_ser,subject_ids_from_hcpcs,right_index=True,left_index=True)
# subject_id_additions_ser
subject_id_additions_ser = icd_procedures_subject_id_ser.append(subject_ids_from_hcpcs,ignore_index=True)

3683

In [24]:
# combining subject IDs (concatenating previous cell)
type(HF_unique_subject_IDs)
subject_id_additions = np.array(subject_id_additions_ser)
all_hip_ids = np.concatenate((HF_unique_subject_IDs,subject_id_additions))

all_hip_ids = [*set(all_hip_ids)]
all_hip_ids = [int(i) for i in all_hip_ids]
# len(all_hip_ids)
all_hip_ids_ser = pd.Series(all_hip_ids)
all_hip_ids_ser.drop_duplicates(keep='first',inplace=True)
len(all_hip_ids_ser)
# all_hip_ids_ser.to_csv('all_hip_ids_ser.csv')

5193

In [ ]:
# looking into outlier prescriptions